SELECT * FROM persona;

SELECT * FROM puesto;

SELECT * FROM trabajador;
SELECT CONCAT(p.`APELLIDOP`,' ',p.`APELLIDOM`,' ',p.`NOMBRES`) FROM trabajador t INNER JOIN persona p ON t.`DNI`=p.`DNI` WHERE idpuesto='203';

SELECT * FROM USUARIO WHERE USUARIO='joshuartero' AND CONTRASEÑA='gunjoshuas';

SELECT * FROM SUPERVISOR_ENOSA;
INSERT INTO SUPERVISOR_ENOSA VALUES ('204','SIESQUEN TUÑOQUE FERNANDO');

SELECT * FROM IMAGEN;

